### PR TITLE
Modify nodes module

### PR DESCRIPTION
**Pull request by 1n4r1**
modified / addedsome functions.

### CODE REVIEW

**Comment by 1n4r1** [comment]
I'll write how to use later...

**Comment by 1n4r1** [comment]
how to use...
```
# initialization
nodes = Nodes(ID_OF_LOCALHOST)

in this situation the data stored is
{"ID_OF_LOCALHOST": {"ID_OF_LOCALHOST": 0}}

# add routing table of other nodes with cost incrementation + 1
nodes.add_table_byte(BYTES, 1)

then, the data from remote is added. 

if we add following bytearray, stored data can be
bytearray("\x42\x42\x42\x42\x42\x42\x42\x42\x30\x30")
↓
[{"nodeself": {"nodeself": 0}},
 {"BBBBBBBB": {"BBBBBBBB": 1}}]

# get full table with byte format
nodes.get_full_table_byte()

# get neighbor to forward the packet
nodes.get_nearest_neighbor(DESTINATION_ID)
```

**Comment by Vearol** [comment]
what does nodes.get_nearest_neighbor(DESTINATION_ID) return?

**Comment by 1n4r1** [comment]
yep, probably need to explain.
but did you read the unit test?
image

**Comment by Vearol** [comment]
yea, well... do you store contacts, separately from the table, so you could get specific ip and port?
what is REALLY needed is live address, of a node, so we need a dictionary, or smth like that, to store relations of id-address

**Comment by 1n4r1** [comment]
this test is expecting this network
image

**Comment by Vearol** [comment]
what is left for us is to have router table live updates, due to specification, and keepalive logic
pls, check specs, maybe I'm missing something
and to have function like nodes.get_nearest_neighbor(DESTINATION_ID), which returns ip and port (pls read previous comment)

**Comment by 1n4r1** [comment]
image
I read your code now.
If my understanding is correct what I can say about ip/port is
"Why do you think I have something you don't provide?"
https://github.com/Vearol/TalTech-Network-Protocol/blob/master/Server%26Client/src/production/packet_handler.py#L50
do you have ip and port in "payload data" ?

**Comment by 1n4r1** [comment]
or these neighbor's ip is fixed from the beginning?

**Comment by Vearol** [comment]
yes, it goes through my handling, but I have other stuff to do
I left the routing part to you, so please do all there is with it
don't you see, that I have done most of work here, so it would be really nice you also could do this part to the end

**Comment by Vearol** [comment]
ip's are fixed, correct

**Comment by 1n4r1** [comment]
What we have agreed on our meeting is "Routing is illiya's part"
image
And I have to mention about this also
image
DON'T SAY "this is your task" about something we have never agreed on as if the decision is already made by us.
especially the last one is just what you did interpret by yourself and based on no fact.


we are working as a team but what you do really looks like pushing tasks on me without any agreement.
really get irritated.

**Comment by 1n4r1** [comment]
these can be a sample of keepalive
https://github.com/inar1/NTP/blob/master/prod/server.py
https://github.com/inar1/NTP/blob/master/prod/subthreads.py

**Comment by Vearol** [comment]
while we were dividing tasks - I had no clue, that Illia is not capable of doing anything, since he had started learning programming this winter. After that, you said, that you will do the routing and I should divide the rest between me and Illia.

Screenshot_16

If I had taken the same angle as you and just said - 'oh, we agreed, that I do this and other is not my part' - we won't have shit, until the deadline. But I want our team to complete this task, and I assumed - you too. But no, you would rather have our team failed this messenger, just to say, that you had your task and not going to do anything else. SO HAPPENED, that there are only two of us, and I thought, that if you see, that I'm trying to finish everything by the time - you would finish that routing part by 100%.

Now to be honest, this part of "Server logic", which we were defining at the start is really small, compare to send/receive and routing. If you don't want to do anything else - fine, I am capable of finishing everything myself, but if you do - please tell me, what are you going to do, so I wouldn't do the same

**Comment by 1n4r1** [comment]
OK, I got what you mean.
At that time I was a bit mad and now I’m calm. Then point out several things
image
In terms of this, you're right and I have to say sorry. I understand you will feel like this.

<br>

image
About this, since we didn't define what is "Routing part" in detail especially the boundary.
So at least I recognize "this person is saying something never agreed".

image
So I prepare tools like getter/setter and I'll explain to you

and also, algorism to calculate neighbor is my responsible.

So this is what I propose
<br>

Summerize:
Followings are my responsibilities
1. getter / setter and function to remove data of IP/ports (don't care about name now
just like 
```
def set_ips(ip_string, port_int)
```
and getter returns tuple is like this
```
def get_ips(destination_id_string):
retrun (127.0.0.1, 8080) 
```
and
```
def remove_neighbor_ips(destination_id_string):
# remove data of ip/port
```

2.  algorism to calculate neighbor
if it had some problem, I'll deal with you

NOT my responsibilities:
1. How / Where to use above getter/setter
2. I don't change the current structure of how to save data of routing table
This means we have <strong> one another "variable" </strong> (dict) for ip/ports

**Comment by Vearol** [comment]
okay, following function interfaces looks fine
there are some things with python, which I don't know, so maybe you could help, an advice or smth... about locks. We have 2 threads for listening socket and reading from keyboard. Since after reading we have to send a message - at the same time we could receive smth in listen thread. I have added the lock, and code works now, just not sure, that in python 
```
with lock:
    do stuff...
```
works how I expect it to work. If you are familiar with it - maybe you know how to do it correctly.
To do it correctly - we needed a giant queue of processing input/output messages, but I didn't do it that way, since we need it just to test in the class. Probably later - I will improve it for myself...

```
NOT my responsibilities:

   1. How use above getter/setter
   2. I don't change the current structure of how to save data of routing table
    This means we have different variable (dict) for ip/ports
```
I don't really understand what you mean in 2. Can you explain, please?

Also, I don't know how to make contact list in a console nicely. Maybe you have some ideas? 
Maybe have smth like:
1. Nickname1
2. Nickname2
3. Nickname3
... and then enter smth like
```
Select destination: 2
```

**Comment by 1n4r1** [comment]
ok, at first talk about something easy
image
this means,
<strong> Now, if we wanna create GUI app for visualization and for end-user controlling, it has to be same process or thread.</strong>

This is because you proposed "in memory storing without any in memory DB" about routing table.

So what I wanna confirm is <strong> you will not say like "this should be accessible from outside of process" later </strong>

**Comment by Vearol** [comment]
About GUI - I don't think, that we time to do that... I don't know any python frameworks, nor have experience with them. I could make smth with Qt, as I remember - it has python support. But right now it's still a lot of tasks to do, so I don't have time for GUI right now.

I proposed in-memory storing, because all we need - is some starting config, where all member will insert their data, so we know which GPG is what destination(ip, port).
And after that - we start exchanging our router table between each other... Of course, this all could be implemented with db, so if you want to do that - please.

**Comment by 1n4r1** [comment]
image
sorry, didn't understand well
for situations like this, what I propose to you is explaining following things
```
1. explaining purpose 
(ex. This is console to chose the destination of user data,
after chosing the destination, we have input from keyboard and send data)
2. which part you really don't like
```

**Comment by 1n4r1** [comment]
image
For this purpose, now we have "global_mapping" (or something like that)
we can save initial data there and read.
and This would be one of my tasks.

<br>

Besides,  what I understood is <strong> currently, I don't have to change it to any other DB products and I don't have to expose it</strong>

**Comment by Vearol** [comment]
1. Purpose
* What we have now? - Hardcoded destination, and input message or filepath from keyboard.
* What we need? - Ability to choose destination before entering text
2. What I don't like
* There will be so many text in command line - it will be hard to recognise stuff.
* Right now, I have added different colors, so I guess for contact list could be just another color?..

If we're writing contacts to console - I suggest to print contact list at start of program, and every time, when routing table is changing

**Pull request merged**
